#!/bin/sh

# Ensure our Magento directory exists
mkdir -p $MAGENTO_ROOT
chown www-data:www-data $MAGENTO_ROOT

# Get fix cron owner and permission
# find -L /var/spool/cron/crontabs -type f -exec sh -c 'chown $(basename {}) {}' \;
find -L /var/spool/cron/crontabs -type f -exec sh -c "chown root:root {}" \;
find -L /var/spool/cron/crontabs -type f -exec sh -c "chmod 0600 {}" \;

# start syslog and cron
syslogd
crond

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

exec "$@"